### ISSUE TITLE
Needs release for new iced coffee script version

### ISSUE THREAD

**Issue by monokrome** [patrickxb/gulp-iced#3]
My [build tool][glp] won't install properly until a new release of `iced-gulp` is available, due to older versions of iced-coffee-script not supporting recent node versions and this plugin's most recent release requiring an older version of it. Is there a chance for a release soon that includes the changes that were [merged 18 days ago][prevpr]?

Thanks for your time!

[glp]: https://github.com/monokrome/glp/
[prevpr]: https://github.com/patrickxb/gulp-iced/pull/2

**Comment by sheldonth** [comment]
+1

**Comment by stephanos** [comment]
+1

**Comment by monokrome** [comment]
Ain't no @patrickxb got time for that

**Comment by nongrata88** [comment]
+1
